### ISSUE TITLE
nicksnyder/go-i18n dependences problem

### ISSUE THREAD

**Issue by colmeirin** [goinggo/beego-mgo#4]
Hi there, I've followed the instructions to install beego-mgo but the following error appears when trying to execute the scripts:

cannot find package "github.com/nicksnyder/go-i18n/i18n/locale" in any of:
    /usr/local/Cellar/go/1.3/libexec/src/pkg/github.com/nicksnyder/go-i18n/i18n/locale (from $GOROOT)
    /Users/######/go/src/github.com/nicksnyder/go-i18n/i18n/locale (from $GOPATH)

I've installed this package but there is no "locale" folder on the project.

Any thoughts?

Regards, Javier.

**Comment by goinggo** [comment]
I will look at this as soon as I get in to work. Thanks for reporting the problem.

**Comment by goinggo** [comment]
The go-i18n package broke compatibility. Major changes. So I vendored the version that works with this code. You should be good to go.

**Comment by colmeirin** [comment]
Thank you for your rapid response. I will check it later and give you some feedback.
Regards.
